Draft security guide
rocket-pool/old.docs.rocketpool.net pull request #11
Opened 2021-04-16 14:32 UTC by actuallymentor

This guide runs through the setting up of some basic security measures for a Rocketpool node, including:

- [ ] SSH keys
- [ ] Disabling password access
- [ ] Enabling auto updates
- [ ] Enabling a firewall
- [ ] Installing and starting `fail2ban`

Let me know if this is the right format and depth for the wiki.

2021-04-16 21:46 UTC, htimsk requested changes
I needed to learn how to do this myself so I am using your instructions as my guide. I am using Win10 as my daily driver and my remote SSH terminal (PUTTY). I'll likely add a similar set of instructions explaining how to create the SSH keys using the PUTTY key generator. I did notice that I think there is a small error in the instructions. 

Line 46 I had to run `nano /etc/ssh/sshd_config` as `sudo nano /etc/ssh/sshd_config` to be able to save the edited file.

Line 49 I believe should be "2. Change `ChallengeResponseAuthentication no` to `ChallengeResponseAuthentication yes`"

2021-04-16 22:03 UTC, htimsk commented on src/guides/node/securing-your-node.md
> +2. Open `/etc/apt/apt.conf.d/20auto-upgrades`, for example with `nano /etc/apt/apt.conf.d/20auto-upgrades` and add your settings, see the block below for a good starting point
FYI: I had to run this with `sudo` otherwise I get this error `[ File '/etc/apt/apt.conf.d/20auto-upgrades' is unwritable ]`

2021-04-19 08:13 UTC, actuallymentor commented
Added your suggestions @htimsk and also started with a paragraph concerning client security as per yorrick's comment on discord.

2021-04-27 13:54 UTC, jhughes-mc commented
Some good open source docs on this. Like: https://github.com/imthenachoman/How-To-Secure-A-Linux-Server

2021-04-28 09:29 UTC, actuallymentor commented
> Some good open source docs on this. Like: [imthenachoman/How-To-Secure-A-Linux-Server](https://github.com/imthenachoman/How-To-Secure-A-Linux-Server)

Yea I like that guide too, referenced it in the [docs file](https://github.com/rocket-pool/rocketpool.github.io/blob/main/src/documentation/smart-node-sections/security-considerations.md) but is may be good to add it here too.

2021-05-03 07:45 UTC, actuallymentor commented
@darcius this is ready for merge as far as I'm concerned :)

2021-05-04 07:14 UTC, darcius commented
Nice work guys!

2021-05-04 07:14 UTC, merged