Tailscale Documentation
rocket-pool/old.docs.rocketpool.net pull request #130
Opened 2022-07-04 03:11 UTC by blinc117

Built off the work initially done by @Grok13 in [PR #82 ](https://github.com/rocket-pool/docs.rocketpool.net/pull/82)

Split out into its own page and added to the menu system, made a few updates as well as reference images.

2022-07-15 07:25 UTC, jclapis commented
@fmoledina @jshufro Can you take a quick look at this?

2022-07-15 07:29 UTC, jshufro commented on src/guides/node/tailscale.md
> +It is suggested to [disable key expiry](https://tailscale.com/kb/1028/key-expiry) to prevent the need to periodically re-authenticate.
specify only to do this for the node

2022-07-15 07:30 UTC, jshufro commented on src/guides/node/tailscale.md
> +You should now be able to `exit` the SSH session to your node on your client, and SSH into your node again through Tailscale using `ssh your.user@rocketnode`.
this kind of assumes magicdns it's enabled, but the guide doesn't say to enable it

2022-07-15 07:33 UTC, jshufro requested changes

2022-07-15 07:33 UTC, jshufro commented on src/guides/node/tailscale.md
> +Remove the SSH port added before from the firewall (for example, if you used the default port of 22):
should leave 22 open to lan, otherwise tailscale becomes a single point of failure

2022-07-15 16:46 UTC, fmoledina commented on src/guides/node/tailscale.md
> +sudo ufw allow 41641/udp
Although the Tailscale [UFW article](https://tailscale.com/kb/1077/secure-server-ubuntu-18-04/) provides this example command, their [firewall](https://tailscale.com/kb/1181/firewalls/) and [ports](https://tailscale.com/kb/1082/firewall-ports/) guides indicate that forwarding 41641/udp is not required unless you're dealing with a problematic NAT environment.

FWIW, I haven't had to forward any ports for Tailscale to _just work_ on the handful of local machines (Linux, Windows) and remote VPS instances that I've used it with.

I think the guide should avoid suggesting that this port be forwarded and instead it could become a support item if people are encountering issues with connectivity.

2022-07-15 16:46 UTC, fmoledina commented on src/guides/node/tailscale.md
> +You should now be able to `exit` the SSH session to your node on your client, and SSH into your node again through Tailscale using `ssh your.user@rocketnode`.
Agreed with this. I think the guide should be clear about this. Perhaps something like 

> ...
> If you would like to access your node using a memorable hostname such as `rocketnode`, you can do so by enabling MagicDNS in the Tailscale settings.
> ...

2023-05-06 23:09 UTC, ryanscovill commented
Picked up this PR in #224

2023-05-30 02:15 UTC, merged